"""auto migration

Revision ID: 0144c897f03d
Revises: e8cb21958410
Create Date: 2026-04-11 08:38:33.574907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0144c897f03d'
down_revision: Union[str, Sequence[str], None] = 'e8cb21958410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_metadata', sa.Column('name_vi', sa.String(), nullable=True))
    op.add_column('food_metadata', sa.Column('name_en', sa.String(), nullable=True))
    op.add_column('food_metadata', sa.Column('kj_per_100g', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_food_metadata_name'), table_name='food_metadata')
    op.create_index(op.f('ix_food_metadata_name_en'), 'food_metadata', ['name_en'], unique=True)
    op.create_index(op.f('ix_food_metadata_name_vi'), 'food_metadata', ['name_vi'], unique=True)
    op.drop_column('food_metadata', 'name')
    op.drop_column('food_metadata', 'ingredients')
    op.drop_column('food_metadata', 'alternate_names')
    op.drop_column('food_metadata', 'description')
    op.add_column('nutrition_metadata', sa.Column('nutrition_class', sa.String(), nullable=True))
    op.create_index(op.f('ix_nutrition_metadata_nutrition_class'), 'nutrition_metadata', ['nutrition_class'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_metadata_nutrition_class'), table_name='nutrition_metadata')
    op.drop_column('nutrition_metadata', 'nutrition_class')
    op.add_column('food_metadata', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('food_metadata', sa.Column('alternate_names', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('food_metadata', sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('food_metadata', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_food_metadata_name_vi'), table_name='food_metadata')
    op.drop_index(op.f('ix_food_metadata_name_en'), table_name='food_metadata')
    op.create_index(op.f('ix_food_metadata_name'), 'food_metadata', ['name'], unique=True)
    op.drop_column('food_metadata', 'kj_per_100g')
    op.drop_column('food_metadata', 'name_en')
    op.drop_column('food_metadata', 'name_vi')
    # ### end Alembic commands ###
