"""auto migration

Revision ID: 0a6a3524eb81
Revises: 
Create Date: 2026-03-25 20:36:26.363868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a6a3524eb81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_metadata',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('alternate_names', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('calories', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_metadata_name'), 'food_metadata', ['name'], unique=True)
    op.create_table('nutrition_metadata',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('nutrition', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_metadata_nutrition'), 'nutrition_metadata', ['nutrition'], unique=True)
    op.create_table('food_nutrients_100g',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('food_id', sa.Uuid(), nullable=True),
        sa.Column('nutrition_id', sa.Uuid(), nullable=True),
        sa.Column('value', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['food_id'], ['food_metadata.id'], ),
        sa.ForeignKeyConstraint(['nutrition_id'], ['nutrition_metadata.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_nutrients_100g')
    op.drop_index(op.f('ix_nutrition_metadata_nutrition'), table_name='nutrition_metadata')
    op.drop_table('nutrition_metadata')
    op.drop_index(op.f('ix_food_metadata_name'), table_name='food_metadata')
    op.drop_table('food_metadata')
    # ### end Alembic commands ###
