"""initial

Revision ID: 3e9bb66dbfcb
Revises: 
Create Date: 2026-06-14 19:38:32.409356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9bb66dbfcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_name_vi', sa.String(), nullable=True),
    sa.Column('category_name_en', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_category_category_name_en'), 'food_category', ['category_name_en'], unique=True)
    op.create_index(op.f('ix_food_category_category_name_vi'), 'food_category', ['category_name_vi'], unique=True)
    op.create_table('nutrition_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nutrition', sa.String(), nullable=True),
    sa.Column('nutrition_class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_metadata_nutrition'), 'nutrition_metadata', ['nutrition'], unique=True)
    op.create_index(op.f('ix_nutrition_metadata_nutrition_class'), 'nutrition_metadata', ['nutrition_class'], unique=False)
    op.create_table('food_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_vi', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('kcal_per_100g', sa.Float(), nullable=True),
    sa.Column('kj_per_100g', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('food_category_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_metadata_name_en'), 'food_metadata', ['name_en'], unique=True)
    op.create_index(op.f('ix_food_metadata_name_vi'), 'food_metadata', ['name_vi'], unique=True)
    op.create_table('food_nutrients_100g',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.Uuid(), nullable=True),
    sa.Column('nutrition_id', sa.Uuid(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food_metadata.id'], ),
    sa.ForeignKeyConstraint(['nutrition_id'], ['nutrition_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_nutrients_100g')
    op.drop_index(op.f('ix_food_metadata_name_vi'), table_name='food_metadata')
    op.drop_index(op.f('ix_food_metadata_name_en'), table_name='food_metadata')
    op.drop_table('food_metadata')
    op.drop_index(op.f('ix_nutrition_metadata_nutrition_class'), table_name='nutrition_metadata')
    op.drop_index(op.f('ix_nutrition_metadata_nutrition'), table_name='nutrition_metadata')
    op.drop_table('nutrition_metadata')
    op.drop_index(op.f('ix_food_category_category_name_vi'), table_name='food_category')
    op.drop_index(op.f('ix_food_category_category_name_en'), table_name='food_category')
    op.drop_table('food_category')
    # ### end Alembic commands ###
