"""auto migration

Revision ID: 6a859f94f072
Revises: 0a6a3524eb81
Create Date: 2026-03-28 18:52:32.470183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a859f94f072'
down_revision: Union[str, Sequence[str], None] = '0a6a3524eb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_metadata_name'), 'country_metadata', ['name'], unique=True)
    op.create_table('food_country',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('food_id', sa.Uuid(), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country_metadata.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_country')
    op.drop_index(op.f('ix_country_metadata_name'), table_name='country_metadata')
    op.drop_table('country_metadata')
    # ### end Alembic commands ###
