"""auto migration

Revision ID: e8cb21958410
Revises: 6a859f94f072
Create Date: 2026-03-28 19:07:12.413777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cb21958410'
down_revision: Union[str, Sequence[str], None] = '6a859f94f072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_metadata', 'calories', new_column_name='kcal_per_100g')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_metadata', 'kcal_per_100g', new_column_name='calories')
    # ### end Alembic commands ###
