from enum import Enum

class ErrorCode(str, Enum):
    # Food related errors
    FOOD_NOT_FOUND = "FOOD_NOT_FOUND"
    FOOD_CREATION_FAILED = "FOOD_CREATION_FAILED"
    FOOD_RECOMMENDATION_FAILED = "FOOD_RECOMMENDATION_FAILED"

    # System errors
    INVALID_REQUEST = "INVALID_REQUEST"
    DATABASE_ERROR = "DATABASE_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    FOOD_DELETION_FAILED = "FOOD_DELETION_FAILED"
    FOOD_UPDATE_FAILED = "FOOD_UPDATE_FAILED"